# Changes here will be overwritten by Copier
AnswerStrategy: recommended
AuthorEmail: mikhail.mikhasenko@gmail.com
AuthorName: Misha Mikhasenko
Indentation: 4
JuliaMinVersion: "1.6"
License: MIT
PackageName: ThreeBodyDecays
PackageOwner: mmikhasenko
PackageUUID: e6563dab-9ca1-5843-bde3-2ccf38d63843
_commit: v0.9.0
_src_path: https://github.com/abelsiqueira/BestieTemplate.jl
